# Register the AgentOS laptop client to start when Calvin logs in (Windows).
#
#   powershell -ExecutionPolicy Bypass -File client\autostart\install-autostart.ps1
#   powershell -ExecutionPolicy Bypass -File client\autostart\install-autostart.ps1 -Uninstall
#
# Pure ASCII on purpose: PS 5.1 reads a .ps1 as cp1252 without a BOM.
# Uses the Startup FOLDER rather than Task Scheduler on purpose: the client needs the
# interactive desktop session (microphone and speakers), and a Task Scheduler job running
# "whether or not the user is logged on" has neither. Startup-folder = same session as you.
#
# Runs hidden via a .vbs shim so you don't get a console window on every login. The log is
# the UI: %LOCALAPPDATA%\AgentOS\laptop.log

param([switch]$Uninstall)

$ErrorActionPreference = "Stop"
$Startup   = [Environment]::GetFolderPath("Startup")
$VbsPath   = Join-Path $Startup "AgentOS.vbs"
$Supervisor = Join-Path $PSScriptRoot "agentos-laptop.ps1"

if ($Uninstall) {
    if (Test-Path $VbsPath) { Remove-Item $VbsPath -Force; Write-Host "Removed $VbsPath" }
    else { Write-Host "Not installed." }
    return
}

if (-not (Test-Path $Supervisor)) { throw "missing $Supervisor" }

# WScript.Shell Run with 0 = hidden window, so login stays clean.
$vbs = @"
' AgentOS laptop client - starts the supervisor hidden at login.
' Generated by install-autostart.ps1. Delete this file to disable autostart.
Set sh = CreateObject("WScript.Shell")
sh.Run "powershell -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File ""$Supervisor""", 0, False
"@
Set-Content -Path $VbsPath -Value $vbs -Encoding ASCII

Write-Host "Installed autostart:"
Write-Host "  $VbsPath"
Write-Host "  -> $Supervisor"
Write-Host ""
Write-Host "Starts at every login. Log: $env:LOCALAPPDATA\AgentOS\laptop.log"
Write-Host "Start it now without logging out:"
Write-Host "  powershell -NoProfile -ExecutionPolicy Bypass -File `"$Supervisor`""
Write-Host "Disable:"
Write-Host "  powershell -ExecutionPolicy Bypass -File `"$PSCommandPath`" -Uninstall"
